{% set version = "1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyjs
  version: {{ version|replace("-", "_") }}

source:
  fn: shinyjs_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinyjs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyjs/shinyjs_{{ version }}.tar.gz
  sha256: 8986181baa68fb2863eea65b9df1b04b9b4e1293685298531d42de3bc2f06892

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest >=0.6.8
    - r-htmltools >=0.2.9
    - r-jsonlite
    - r-shiny >=1.0.0
  run:
    - r-base
    - r-digest >=0.6.8
    - r-htmltools >=0.2.9
    - r-jsonlite
    - r-shiny >=1.0.0

test:
  commands:
    - $R -e "library('shinyjs')"           # [not win]
    - "\"%R%\" -e \"library('shinyjs')\""  # [win]

about:
  home: https://deanattali.com/shinyjs
  license: AGPL-3
  summary: 'Perform common useful JavaScript operations in Shiny apps that will greatly improve
    your apps without having to know any JavaScript. Examples include: hiding an element,
    disabling an input, resetting an input back to its original value, delaying code
    execution by a few seconds, and many more useful functions for both the end user
    and the developer. ''shinyjs'' can also be used to easily call your own custom JavaScript
    functions from R.'
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
