appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mGY0XDcba6sdJPTR4FZxDjC7oWuQeNiFdWujXWyk/pjdovzGan4udXPCSvo76nfSWOWnyglgO7Eu7be8r/G1nwudEnMqiRXzbz/8V3/dfcPafjBmavEvsC9E76R9nILSSGq2yHHrKe0YlXUhHtFujBTyMDLFhW13AEbH9DoMwNqkLPcOVvqq/4FUiXCEZfckoiADmU/cpblPeqi2IRAP2J3HxysGhc1F3a4QcPB44ZU9/UB106UVrNBCo5i9tn/qr+XabRkcm/9OeZMEEoGNOnhSF8oEmUo+oy5fGmQYplKn7t5PgPTcx3YwrFVS7G4+BYz7N4q0FkJOhn4ZjeP+FMCEONHAsKE16VXXf/TAq8kQOLS/8EEWpkCgqNKLs7jbynUd5ENaza4b5LGXOO5Jvgix8GEEIpvyR3p34OIUItEEvvN9opoJQiRhzVjlXdHf5tW+T+Xo1fX+agcBk8OaU0QXXA4YibVrdr4CeYzIfxPQPI1t3mlFaROER7tzm8ky81OkEpXtyPrudHEQkFvBZMtoPPWiZvXurLfGbqNLGrX2blj1puIgtSxZfC2Vn7nT9ouWwzvrySyYlFVtO0MIUI3/z5EBW+5bGOSKvudNZrb8ADrAWCdxkhyvawCs0xzye2zOduDPfv8TA3mbfgpaVEZsz5l8Od+xDP7Z5vLpG7Y=
conda_forge_output_validation: false
